<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>ALGO_ERROR</source>
      <translation>ALGO_ERROR</translation>
    </message>
    <message>
      <source>EXPORT_ERROR</source>
      <translation>EXPORT_ERROR</translation>
    </message>
    <message>
      <source>IMPORT_ERROR</source>
      <translation>IMPORT_ERROR</translation>
    </message>
  </context>
  <context>
    <name>ATOMGENGUI</name>
    <message>
      <source>EXPORT_XML</source>
      <translation>EXPORT_XML</translation>
    </message>
    <message>
      <source>IMPORT_XML</source>
      <translation>IMPORT_XML</translation>
    </message>
    <message>
      <source>MEN_EXPORT_XML</source>
      <translation>MEN_EXPORT_XML</translation>
    </message>
    <message>
      <source>MEN_FILE</source>
      <translation>MEN_FILE</translation>
    </message>
    <message>
      <source>MEN_IMPORT_XML</source>
      <translation>MEN_IMPORT_XML</translation>
    </message>
    <message>
      <source>STB_EXPORT_XML</source>
      <translation>STB_EXPORT_XML</translation>
    </message>
    <message>
      <source>STB_IMPORT_XML</source>
      <translation>STB_IMPORT_XML</translation>
    </message>
    <message>
      <source>TOP_EXPORT_XML</source>
      <translation>TOP_EXPORT_XML</translation>
    </message>
    <message>
      <source>TOP_IMPORT_XML</source>
      <translation>TOP_IMPORT_XML</translation>
    </message>
    <message>
      <source>WARNING</source>
      <translation>WARNING</translation>
    </message>
    <message>
      <source>XML_FILES</source>
      <translation>XML_FILES</translation>
    </message>
  </context>
</TS>
