<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>HEXABLOCK_ADV_ARGS</source>
      <translation>HEXABLOCK_ADV_ARGS</translation>
    </message>
    <message>
      <source>HEXABLOCK_HYPOTHESIS</source>
      <translation>HEXABLOCK_HYPOTHESIS</translation>
    </message>
    <message>
      <source>HEXABLOCK_OPTIMIZATIOL_LEVEL</source>
      <translation>HEXABLOCK_OPTIMIZATIOL_LEVEL</translation>
    </message>
    <message>
      <source>HEXABLOCK_PERMISSION_DENIED</source>
      <translation>HEXABLOCK_PERMISSION_DENIED</translation>
    </message>
    <message>
      <source>HEXABLOCK_STD_ARGS</source>
      <translation>HEXABLOCK_STD_ARGS</translation>
    </message>
    <message>
      <source>HEXABLOCK_TITLE</source>
      <translation>HEXABLOCK_TITLE</translation>
    </message>
    <message>
      <source>HEXABLOCK_TO_MESH_HOLES</source>
      <translation>HEXABLOCK_TO_MESH_HOLES</translation>
    </message>
    <message>
      <source>INIT_MEMORY_SIZE</source>
      <translation>INIT_MEMORY_SIZE</translation>
    </message>
    <message>
      <source>KEEP_WORKING_FILES</source>
      <translation>KEEP_WORKING_FILES</translation>
    </message>
    <message>
      <source>LEVEL_NONE</source>
      <translation>LEVEL_NONE</translation>
    </message>
    <message>
      <source>LEVEL_LIGHT</source>
      <translation>LEVEL_LIGHT</translation>
    </message>
    <message>
      <source>LEVEL_MEDIUM</source>
      <translation>LEVEL_MEDIUM</translation>
    </message>
    <message>
      <source>LEVEL_STANDARDPLUS</source>
      <translation>LEVEL_STANDARDPLUS</translation>
    </message>
    <message>
      <source>LEVEL_STRONG</source>
      <translation>LEVEL_STRONG</translation>
    </message>
    <message>
      <source>MAX_MEMORY_SIZE</source>
      <translation>MAX_MEMORY_SIZE</translation>
    </message>
    <message>
      <source>MEGABYTE</source>
      <translation>MEGABYTE</translation>
    </message>
    <message>
      <source>NO_INITIAL_CENTRAL_POINT</source>
      <translation>NO_INITIAL_CENTRAL_POINT</translation>
    </message>
    <message>
      <source>RECOVERY_VERSION</source>
      <translation>RECOVERY_VERSION</translation>
    </message>
    <message>
      <source>FEM_CORRECTION</source>
      <translation>FEM_CORRECTION</translation>
    </message>
    <message>
      <source>SELECT_DIR</source>
      <translation>SELECT_DIR</translation>
    </message>
    <message>
      <source>TEXT_OPTION</source>
      <translation>TEXT_OPTION</translation>
    </message>
    <message>
      <source>TO_ADD_NODES</source>
      <translation>TO_ADD_NODES</translation>
    </message>
    <message>
      <source>VERBOSE_LEVEL</source>
      <translation>VERBOSE_LEVEL</translation>
    </message>
    <message>
      <source>WORKING_DIR</source>
      <translation>WORKING_DIR</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENFORCED_VERTICES</source>
      <translation>HEXABLOCK_ENFORCED_VERTICES</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_X_COLUMN</source>
      <translation>HEXABLOCK_ENF_VER_X_COLUMN</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Y_COLUMN</source>
      <translation>HEXABLOCK_ENF_VER_Y_COLUMN</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Z_COLUMN</source>
      <translation>HEXABLOCK_ENF_VER_Z_COLUMN</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_SIZE_COLUMN</source>
      <translation>HEXABLOCK_ENF_VER_SIZE_COLUMN</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_X_LABEL</source>
      <translation>HEXABLOCK_ENF_VER_X_LABEL</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Y_LABEL</source>
      <translation>HEXABLOCK_ENF_VER_Y_LABEL</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Z_LABEL</source>
      <translation>HEXABLOCK_ENF_VER_Z_LABEL</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_SIZE_LABEL</source>
      <translation>HEXABLOCK_ENF_VER_SIZE_LABEL</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_VERTEX</source>
      <translation>HEXABLOCK_ENF_VER_VERTEX</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_REMOVE</source>
      <translation>HEXABLOCK_ENF_VER_REMOVE</translation>
    </message>
  </context>
</TS>
