<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>ATOM</source>
      <translation>ATOM</translation>
    </message>
    <message>
      <source>ATOMSOLV_PREFERENCES</source>
      <translation>ATOMSOLV_PREFERENCES</translation>
    </message>
    <message>
      <source>DISPLAY_MODE_PREF</source>
      <translation>DISPLAY_MODE_PREF</translation>
    </message>
    <message>
      <source>MEN_ATOMSOLV</source>
      <translation>MEN_ATOMSOLV</translation>
    </message>
    <message>
      <source>MEN_COLOR</source>
      <translation>MEN_COLOR</translation>
    </message>
    <message>
      <source>MEN_DISPLAY</source>
      <translation>MEN_DISPLAY</translation>
    </message>
    <message>
      <source>MEN_DISPLAY_MODE</source>
      <translation>MEN_DISPLAY_MODE</translation>
    </message>
    <message>
      <source>MEN_ERASE</source>
      <translation>MEN_ERASE</translation>
    </message>
    <message>
      <source>MEN_POINTSMODE</source>
      <translation>MEN_POINTSMODE</translation>
    </message>
    <message>
      <source>MEN_PROCESS_DATA</source>
      <translation>MEN_PROCESS_DATA</translation>
    </message>
    <message>
      <source>MEN_RETRIEVE_DATA</source>
      <translation>MEN_RETRIEVE_DATA</translation>
    </message>
    <message>
      <source>MEN_SHADING</source>
      <translation>MEN_SHADING</translation>
    </message>
    <message>
      <source>MEN_TRANSPARENCY</source>
      <translation>MEN_TRANSPARENCY</translation>
    </message>
    <message>
      <source>MEN_WIREFRAME</source>
      <translation>MEN_WIREFRAME</translation>
    </message>
    <message>
      <source>MOLECULE</source>
      <translation>MOLECULE</translation>
    </message>
    <message>
      <source>PRESENTATION_PREF_GROUP</source>
      <translation>PRESENTATION_PREF_GROUP</translation>
    </message>
    <message>
      <source>RADIUS_PREF</source>
      <translation>RADIUS_PREF</translation>
    </message>
    <message>
      <source>STS_COLOR</source>
      <translation>STS_COLOR</translation>
    </message>
    <message>
      <source>STS_DISPLAY</source>
      <translation>STS_DISPLAY</translation>
    </message>
    <message>
      <source>STS_ERASE</source>
      <translation>STS_ERASE</translation>
    </message>
    <message>
      <source>STS_POINTSMODE</source>
      <translation>STS_POINTSMODE</translation>
    </message>
    <message>
      <source>STS_PROCESS_DATA</source>
      <translation>STS_PROCESS_DATA</translation>
    </message>
    <message>
      <source>STS_RETRIEVE_DATA</source>
      <translation>STS_RETRIEVE_DATA</translation>
    </message>
    <message>
      <source>STS_SHADING</source>
      <translation>STS_SHADING</translation>
    </message>
    <message>
      <source>STS_TRANSPARENCY</source>
      <translation>STS_TRANSPARENCY</translation>
    </message>
    <message>
      <source>STS_WIREFRAME</source>
      <translation>STS_WIREFRAME</translation>
    </message>
    <message>
      <source>TLT_COLOR</source>
      <translation>TLT_COLOR</translation>
    </message>
    <message>
      <source>TLT_DISPLAY</source>
      <translation>TLT_DISPLAY</translation>
    </message>
    <message>
      <source>TLT_ERASE</source>
      <translation>TLT_ERASE</translation>
    </message>
    <message>
      <source>TLT_POINTSMODE</source>
      <translation>TLT_POINTSMODE</translation>
    </message>
    <message>
      <source>TLT_PROCESS_DATA</source>
      <translation>TLT_PROCESS_DATA</translation>
    </message>
    <message>
      <source>TLT_RETRIEVE_DATA</source>
      <translation>TLT_RETRIEVE_DATA</translation>
    </message>
    <message>
      <source>TLT_SHADING</source>
      <translation>TLT_SHADING</translation>
    </message>
    <message>
      <source>TLT_TRANSPARENCY</source>
      <translation>TLT_TRANSPARENCY</translation>
    </message>
    <message>
      <source>TLT_WIREFRAME</source>
      <translation>TLT_WIREFRAME</translation>
    </message>
    <message>
      <source>TOOL_ATOMSOLV</source>
      <translation>TOOL_ATOMSOLV</translation>
    </message>
    <message>
      <source>TRANSPARENCY_DLG_TITLE</source>
      <translation>TRANSPARENCY_DLG_TITLE</translation>
    </message>
    <message>
      <source>TRANSPARENCY_OPAQUE</source>
      <translation>TRANSPARENCY_OPAQUE</translation>
    </message>
    <message>
      <source>TRANSPARENCY_TRANSPARENT</source>
      <translation>TRANSPARENCY_TRANSPARENT</translation>
    </message>
  </context>
</TS>
