<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>ViewerTools_CubeAxesDlgBase</name>
    <message>
      <source>X_AXIS</source>
      <translation>X-Achse</translation>
    </message>
    <message>
      <source>Y_AXIS</source>
      <translation>Y Achse</translation>
    </message>
    <message>
      <source>Z_AXIS</source>
      <translation>Z-Achse</translation>
    </message>
    <message>
      <source>CAPTION</source>
      <translation>Abgestufte Achsen</translation>
    </message>
    <message>
      <source>IS_VISIBLE</source>
      <translation>Ist sichtbar</translation>
    </message>
    <message>
      <source>FONT</source>
      <translation>Schriftart</translation>
    </message>
    <message>
      <source>NAME</source>
      <translation>Name</translation>
    </message>
    <message>
      <source>TICK_MARKS</source>
      <translation>Teilstriche</translation>
    </message>
    <message>
      <source>LABELS</source>
      <translation>Etiketten</translation>
    </message>
    <message>
      <source>LENGTH</source>
      <translation>Länge</translation>
    </message>
    <message>
      <source>NUMBER</source>
      <translation>Anzahl</translation>
    </message>
    <message>
      <source>OFFSET</source>
      <translation>Versatz</translation>
    </message>
    <message>
      <source>AXIS_NAME</source>
      <translation>Achsenname</translation>
    </message>
  </context>
  <context>
    <name>ViewerTools_FontWidgetBase</name>
    <message>
      <source>BOLD</source>
      <translation>Kühn</translation>
    </message>
    <message>
      <source>ITALIC</source>
      <translation>Italic</translation>
    </message>
    <message>
      <source>SHADOW</source>
      <translation>Schatten</translation>
    </message>
  </context>
</TS>
