<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>HOM_MEN_HOMARD</source>
      <translation>カナダ産オマール海老</translation>
    </message>
    <message>
      <source>HOM_MEN_NEW_CASE</source>
      <translation>新しいケース</translation>
    </message>
    <message>
      <source>HOM_MEN_NEW_ITERATION</source>
      <translation>次の反復処理</translation>
    </message>
    <message>
      <source>HOM_MEN_COMPUTE</source>
      <translation>計算</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_CASE</source>
      <translation>場合を編集します。</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_ITERATION</source>
      <translation>イテレーションを編集します。</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_HYPO</source>
      <translation>仮説を編集します。</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_ZONE</source>
      <translation>ゾーンを編集します。</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_BOUNDARY</source>
      <translation>境界を編集します。</translation>
    </message>
    <message>
      <source>HOM_MEN_EDIT_MESS_FILE</source>
      <translation>ファイルを表示します。</translation>
    </message>
    <message>
      <source>HOM_TOP_HOMARD</source>
      <translation>カナダ産オマール海老</translation>
    </message>
    <message>
      <source>HOM_TOP_NEW_CASE</source>
      <translation>新しいケース</translation>
    </message>
    <message>
      <source>HOM_TOP_NEW_ITERATION</source>
      <translation>次の反復処理</translation>
    </message>
    <message>
      <source>HOM_TOP_COMPUTE</source>
      <translation>計算</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_CASE</source>
      <translation>場合を編集します。</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_ITERATION</source>
      <translation>イテレーションを編集します。</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_HYPO</source>
      <translation>仮説を編集します。</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_ZONE</source>
      <translation>ゾーンを編集します。</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_BOUNDARY</source>
      <translation>境界を編集します。</translation>
    </message>
    <message>
      <source>HOM_TOP_EDIT_MESS_FILE</source>
      <translation>ファイルを表示します。</translation>
    </message>
    <message>
      <source>HOM_STB_HOMARD</source>
      <translation>カナダ産オマール海老</translation>
    </message>
    <message>
      <source>HOM_STB_NEW_CASE</source>
      <translation>新しいケース</translation>
    </message>
    <message>
      <source>HOM_STB_NEW_ITERATION</source>
      <translation>次の反復処理</translation>
    </message>
    <message>
      <source>HOM_STB_COMPUTE</source>
      <translation>計算</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_CASE</source>
      <translation>場合を編集します。</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_ITERATION</source>
      <translation>イテレーションを編集します。</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_HYPO</source>
      <translation>仮説を編集します。</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_ZONE</source>
      <translation>ゾーンを編集します。</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_BOUNDARY</source>
      <translation>境界を編集します。</translation>
    </message>
    <message>
      <source>HOM_STB_EDIT_MESS_FILE</source>
      <translation>ファイルを表示します。</translation>
    </message>
    <message>
      <source>HOM_WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>HOM_ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>HOM_INACTIVE_BUTTON</source>
      <translation>アクティブでないボタン</translation>
    </message>
    <message>
      <source>HOM_SELECT_OBJECT_1</source>
      <translation>オブジェクトを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_OBJECT_2</source>
      <translation>1 つのオブジェクトを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_OBJECT_3</source>
      <translation>オブジェクト型%1 を選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_FILE_1</source>
      <translation>ファイルを選択します。</translation>
    </message>
    <message>
      <source>HOM_SELECT_FILE_2</source>
      <translation>1 つのファイルを選択します。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_1</source>
      <translation>この医学ファイルを読み取ることができません。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_2</source>
      <translation>この医学ファイルないメッシュ。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_3</source>
      <translation>1 つ以上のメッシュこの MED のファイル。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_4</source>
      <translation>この医学ファイルのメッシュを読み取ることができません。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_5</source>
      <translation>この医学ファイル内のフィールドがありません。</translation>
    </message>
    <message>
      <source>HOM_MED_FILE_6</source>
      <translation>この医学ファイル内のフィールドを読み取ることができません。</translation>
    </message>
    <message>
      <source>HOM_SELECT_STUDY</source>
      <translation>研究オブジェクトと関連付けられている医学ファイル \n を選択または医学ファイルを選択します。</translation>
    </message>
    <message>
      <source>HOM_CASE_NAME</source>
      <translation>場合を名前する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_1</source>
      <translation>場合のディレクトリを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_2</source>
      <translation>このディレクトリは既に使用います。</translation>
    </message>
    <message>
      <source>HOM_CASE_DIRECTORY_3</source>
      <translation>場合の有効なディレクトリを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_MESH</source>
      <translation>初期メッシュのファイルを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_CASE_GROUP</source>
      <translation>グループ「%1」以上 1 の境界を指定ことはできません。</translation>
    </message>
    <message>
      <source>HOM_CASE_EDIT_WINDOW_TITLE</source>
      <translation>場合の版</translation>
    </message>
    <message>
      <source>HOM_ITER_NAME</source>
      <translation>イテレーションを名前する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT</source>
      <translation>以前のイテレーションを指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_MESH</source>
      <translation>最終的なメッシュを名前します。</translation>
    </message>
    <message>
      <source>HOM_ITER_HYPO</source>
      <translation>仮説を選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_FIELD_FILE</source>
      <translation>この仮説とは、フィールドのファイル指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT_0</source>
      <translation>メッシュ</translation>
    </message>
    <message>
      <source>HOM_ITER_STARTING_POINT_1</source>
      <translation>最初のイテレーションの場合</translation>
    </message>
    <message>
      <source>HOM_ITER_EDIT_WINDOW_TITLE</source>
      <translation>イテレーションの版</translation>
    </message>
    <message>
      <source>HOM_HYPO_NAME</source>
      <translation>仮説を名前する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_FIELD_FILE</source>
      <translation>フィールドのファイルを指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_ZONE_1</source>
      <translation>ゾーンを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_ZONE_2</source>
      <translation>少なくとも、1 つのゾーンを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_ZONE_3</source>
      <translation>いずれか洗練された， が両方ではないです。</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_L2</source>
      <translation>L2 規範</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_INF</source>
      <translation>無限の規範</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_ABS</source>
      <translation>絶対</translation>
    </message>
    <message>
      <source>HOM_HYPO_NORM_REL</source>
      <translation>相対</translation>
    </message>
    <message>
      <source>HOM_HYPO_COMP</source>
      <translation>少なくとも、1 つのコンポーネントを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_HYPO_EDIT_WINDOW_TITLE</source>
      <translation>仮説の版</translation>
    </message>
    <message>
      <source>HOM_ZONE_NAME</source>
      <translation>ゾーンを指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_ZONE_LIMIT</source>
      <translation>%1 マキシ%1 ミニよりも大きくする必要があります。</translation>
    </message>
    <message>
      <source>HOM_ZONE_RAYON</source>
      <translation>外部の半径は、内部の半径よりも大きくなければなりません。</translation>
    </message>
    <message>
      <source>HOM_ZONE_EDIT_WINDOW_TITLE</source>
      <translation>ゾーンの版</translation>
    </message>
    <message>
      <source>HOM_BOUN_NAME</source>
      <translation>境界を指定する必要があります。</translation>
    </message>
    <message>
      <source>HOM_BOUN_MESH</source>
      <translation>境界のメッシュのファイルを選択する必要があります。</translation>
    </message>
    <message>
      <source>HOM_BOUN_CASE</source>
      <translation>ケースの meshfile が知られています。</translation>
    </message>
    <message>
      <source>HOM_AXE</source>
      <translation>軸は非 0 のベクトルである必要があります。</translation>
    </message>
    <message>
      <source>HOM_BOUN_A_EDIT_WINDOW_TITLE</source>
      <translation>解析的境界の版</translation>
    </message>
    <message>
      <source>HOM_BOUN_D_EDIT_WINDOW_TITLE</source>
      <translation>離散境界の版</translation>
    </message>
    <message>
      <source>HOM_GROU_EDIT_WINDOW_TITLE</source>
      <translation>選択したグループ</translation>
    </message>
  </context>
</TS>
