<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>ATOM</source>
      <translation>原子</translation>
    </message>
    <message>
      <source>ATOMSOLV_PREFERENCES</source>
      <translation>ATOMSOLV</translation>
    </message>
    <message>
      <source>DISPLAY_MODE_PREF</source>
      <translation>既定の表示モード</translation>
    </message>
    <message>
      <source>MEN_ATOMSOLV</source>
      <translation>AtomSolv</translation>
    </message>
    <message>
      <source>MEN_COLOR</source>
      <translation>色</translation>
    </message>
    <message>
      <source>MEN_DISPLAY</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>MEN_DISPLAY_MODE</source>
      <translation>表示モード</translation>
    </message>
    <message>
      <source>MEN_ERASE</source>
      <translation>消去</translation>
    </message>
    <message>
      <source>MEN_POINTSMODE</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>MEN_PROCESS_DATA</source>
      <translation>プロセス データ</translation>
    </message>
    <message>
      <source>MEN_RETRIEVE_DATA</source>
      <translation>データを取得します。</translation>
    </message>
    <message>
      <source>MEN_SHADING</source>
      <translation>表面</translation>
    </message>
    <message>
      <source>MEN_TRANSPARENCY</source>
      <translation>透明性</translation>
    </message>
    <message>
      <source>MEN_WIREFRAME</source>
      <translation>ワイヤ フレーム</translation>
    </message>
    <message>
      <source>MOLECULE</source>
      <translation>分子</translation>
    </message>
    <message>
      <source>PRESENTATION_PREF_GROUP</source>
      <translation>原子プレゼンテーション</translation>
    </message>
    <message>
      <source>RADIUS_PREF</source>
      <translation>デフォルトの半径</translation>
    </message>
    <message>
      <source>STS_COLOR</source>
      <translation>色の設定</translation>
    </message>
    <message>
      <source>STS_DISPLAY</source>
      <translation>表示原子</translation>
    </message>
    <message>
      <source>STS_ERASE</source>
      <translation>原子を消去します。</translation>
    </message>
    <message>
      <source>STS_POINTSMODE</source>
      <translation>セット ポイント表現モード</translation>
    </message>
    <message>
      <source>STS_PROCESS_DATA</source>
      <translation>プロセス データ</translation>
    </message>
    <message>
      <source>STS_RETRIEVE_DATA</source>
      <translation>データを取得します。</translation>
    </message>
    <message>
      <source>STS_SHADING</source>
      <translation>セットの表面表現モード</translation>
    </message>
    <message>
      <source>STS_TRANSPARENCY</source>
      <translation>透明度の設定</translation>
    </message>
    <message>
      <source>STS_WIREFRAME</source>
      <translation>ワイヤ フレーム表示モードを設定します。</translation>
    </message>
    <message>
      <source>TLT_COLOR</source>
      <translation>色</translation>
    </message>
    <message>
      <source>TLT_DISPLAY</source>
      <translation>表示原子</translation>
    </message>
    <message>
      <source>TLT_ERASE</source>
      <translation>原子を消去します。</translation>
    </message>
    <message>
      <source>TLT_POINTSMODE</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>TLT_PROCESS_DATA</source>
      <translation>プロセス データ</translation>
    </message>
    <message>
      <source>TLT_RETRIEVE_DATA</source>
      <translation>データを取得します。</translation>
    </message>
    <message>
      <source>TLT_SHADING</source>
      <translation>表面</translation>
    </message>
    <message>
      <source>TLT_TRANSPARENCY</source>
      <translation>透明性</translation>
    </message>
    <message>
      <source>TLT_WIREFRAME</source>
      <translation>ワイヤ フレーム</translation>
    </message>
    <message>
      <source>TOOL_ATOMSOLV</source>
      <translation>AtomSolv</translation>
    </message>
    <message>
      <source>TRANSPARENCY_DLG_TITLE</source>
      <translation>透明度の設定</translation>
    </message>
    <message>
      <source>TRANSPARENCY_OPAQUE</source>
      <translation>不透明</translation>
    </message>
    <message>
      <source>TRANSPARENCY_TRANSPARENT</source>
      <translation>透明</translation>
    </message>
  </context>
</TS>
