<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>ATOM</source>
      <translation>Atom</translation>
    </message>
    <message>
      <source>ATOMSOLV_PREFERENCES</source>
      <translation>ATOMSOLV</translation>
    </message>
    <message>
      <source>DISPLAY_MODE_PREF</source>
      <translation>Standardanzeigemodus</translation>
    </message>
    <message>
      <source>MEN_ATOMSOLV</source>
      <translation>AtomSolv</translation>
    </message>
    <message>
      <source>MEN_COLOR</source>
      <translation>Farbe</translation>
    </message>
    <message>
      <source>MEN_DISPLAY</source>
      <translation>Display</translation>
    </message>
    <message>
      <source>MEN_DISPLAY_MODE</source>
      <translation>Anzeigemodus</translation>
    </message>
    <message>
      <source>MEN_ERASE</source>
      <translation>Löschen</translation>
    </message>
    <message>
      <source>MEN_POINTSMODE</source>
      <translation>Punkte</translation>
    </message>
    <message>
      <source>MEN_PROCESS_DATA</source>
      <translation>Prozessdaten</translation>
    </message>
    <message>
      <source>MEN_RETRIEVE_DATA</source>
      <translation>Abrufen von Daten</translation>
    </message>
    <message>
      <source>MEN_SHADING</source>
      <translation>Oberfläche</translation>
    </message>
    <message>
      <source>MEN_TRANSPARENCY</source>
      <translation>Transparenz</translation>
    </message>
    <message>
      <source>MEN_WIREFRAME</source>
      <translation>"Drahtmodell"</translation>
    </message>
    <message>
      <source>MOLECULE</source>
      <translation>Molekül</translation>
    </message>
    <message>
      <source>PRESENTATION_PREF_GROUP</source>
      <translation>Atome-Präsentation</translation>
    </message>
    <message>
      <source>RADIUS_PREF</source>
      <translation>Standardradius</translation>
    </message>
    <message>
      <source>STS_COLOR</source>
      <translation>Festlegen der Farbe</translation>
    </message>
    <message>
      <source>STS_DISPLAY</source>
      <translation>Display-atom</translation>
    </message>
    <message>
      <source>STS_ERASE</source>
      <translation>Atom zu löschen</translation>
    </message>
    <message>
      <source>STS_POINTSMODE</source>
      <translation>Sollwerte Darstellung Modus</translation>
    </message>
    <message>
      <source>STS_PROCESS_DATA</source>
      <translation>Prozessdaten</translation>
    </message>
    <message>
      <source>STS_RETRIEVE_DATA</source>
      <translation>Abrufen von Daten</translation>
    </message>
    <message>
      <source>STS_SHADING</source>
      <translation>Set Darstellung-Modus</translation>
    </message>
    <message>
      <source>STS_TRANSPARENCY</source>
      <translation>Set Transparenz</translation>
    </message>
    <message>
      <source>STS_WIREFRAME</source>
      <translation>Set Drahtmodellmodus Darstellung</translation>
    </message>
    <message>
      <source>TLT_COLOR</source>
      <translation>Farbe</translation>
    </message>
    <message>
      <source>TLT_DISPLAY</source>
      <translation>Display-atom</translation>
    </message>
    <message>
      <source>TLT_ERASE</source>
      <translation>Atom zu löschen</translation>
    </message>
    <message>
      <source>TLT_POINTSMODE</source>
      <translation>Punkte</translation>
    </message>
    <message>
      <source>TLT_PROCESS_DATA</source>
      <translation>Prozessdaten</translation>
    </message>
    <message>
      <source>TLT_RETRIEVE_DATA</source>
      <translation>Abrufen von Daten</translation>
    </message>
    <message>
      <source>TLT_SHADING</source>
      <translation>Oberfläche</translation>
    </message>
    <message>
      <source>TLT_TRANSPARENCY</source>
      <translation>Transparenz</translation>
    </message>
    <message>
      <source>TLT_WIREFRAME</source>
      <translation>"Drahtmodell"</translation>
    </message>
    <message>
      <source>TOOL_ATOMSOLV</source>
      <translation>AtomSolv</translation>
    </message>
    <message>
      <source>TRANSPARENCY_DLG_TITLE</source>
      <translation>Set Transparenz</translation>
    </message>
    <message>
      <source>TRANSPARENCY_OPAQUE</source>
      <translation>Deckend</translation>
    </message>
    <message>
      <source>TRANSPARENCY_TRANSPARENT</source>
      <translation>Transparent</translation>
    </message>
  </context>
</TS>
