<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>ATOMICGUI_EXPORT_XML</source>
      <translation>ATOMICGUI_EXPORT_XML</translation>
    </message>
    <message>
      <source>ATOMICGUI_IMPORT_XML</source>
      <translation>ATOMICGUI_IMPORT_XML</translation>
    </message>
    <message>
      <source>ATOMICGUI_NEW_NAME</source>
      <translation>ATOMICGUI_NEW_NAME</translation>
    </message>
    <message>
      <source>ATOMICGUI_NONAME</source>
      <translation>ATOMICGUI_NONAME</translation>
    </message>
    <message>
      <source>ATOMICGUI_RENAME_OBJECT</source>
      <translation>ATOMICGUI_RENAME_OBJECT</translation>
    </message>
    <message>
      <source>ATOMIC_ATOM</source>
      <translation>ATOMIC_ATOM</translation>
    </message>
    <message>
      <source>ATOMIC_MOLECULE</source>
      <translation>ATOMIC_MOLECULE</translation>
    </message>
    <message>
      <source>ATOMIC_ROOT_TOOLTIP</source>
      <translation>ATOMIC_ROOT_TOOLTIP</translation>
    </message>
    <message>
      <source>BUT_OK</source>
      <translation>BUT_OK</translation>
    </message>
    <message>
      <source>MEN_FILE</source>
      <translation>MEN_FILE</translation>
    </message>
    <message>
      <source>WRN_EXPORT_FAILED</source>
      <translation>WRN_EXPORT_FAILED</translation>
    </message>
    <message>
      <source>WRN_IMPORT_FAILED</source>
      <translation>WRN_IMPORT_FAILED</translation>
    </message>
    <message>
      <source>WRN_WARNING</source>
      <translation>WRN_WARNING</translation>
    </message>
    <message>
      <source>XML_FILES</source>
      <translation>XML_FILES</translation>
    </message>
  </context>
  <context>
    <name>ATOMICGUI</name>
    <message>
      <source>MEN_ADD_ATOM</source>
      <translation>MEN_ADD_ATOM</translation>
    </message>
    <message>
      <source>MEN_ATOMIC</source>
      <translation>MEN_ATOMIC</translation>
    </message>
    <message>
      <source>MEN_CREATE_MOL</source>
      <translation>MEN_CREATE_MOL</translation>
    </message>
    <message>
      <source>MEN_DELETE_OBJ</source>
      <translation>MEN_DELETE_OBJ</translation>
    </message>
    <message>
      <source>MEN_EDIT</source>
      <translation>MEN_EDIT</translation>
    </message>
    <message>
      <source>MEN_EXPORT_XML</source>
      <translation>MEN_EXPORT_XML</translation>
    </message>
    <message>
      <source>MEN_IMPORT_XML</source>
      <translation>MEN_IMPORT_XML</translation>
    </message>
    <message>
      <source>MEN_RENAME</source>
      <translation>MEN_RENAME</translation>
    </message>
    <message>
      <source>STB_ADD_ATOM</source>
      <translation>STB_ADD_ATOM</translation>
    </message>
    <message>
      <source>STB_CREATE_MOL</source>
      <translation>STB_CREATE_MOL</translation>
    </message>
    <message>
      <source>STB_DELETE_OBJ</source>
      <translation>STB_DELETE_OBJ</translation>
    </message>
    <message>
      <source>STB_EXPORT_XML</source>
      <translation>STB_EXPORT_XML</translation>
    </message>
    <message>
      <source>STB_IMPORT_XML</source>
      <translation>STB_IMPORT_XML</translation>
    </message>
    <message>
      <source>STB_RENAME</source>
      <translation>STB_RENAME</translation>
    </message>
    <message>
      <source>TOP_ADD_ATOM</source>
      <translation>TOP_ADD_ATOM</translation>
    </message>
    <message>
      <source>TOP_CREATE_MOL</source>
      <translation>TOP_CREATE_MOL</translation>
    </message>
    <message>
      <source>TOP_DELETE_OBJ</source>
      <translation>TOP_DELETE_OBJ</translation>
    </message>
    <message>
      <source>TOP_EXPORT_XML</source>
      <translation>TOP_EXPORT_XML</translation>
    </message>
    <message>
      <source>TOP_IMPORT_XML</source>
      <translation>TOP_IMPORT_XML</translation>
    </message>
    <message>
      <source>TOP_RENAME</source>
      <translation>TOP_RENAME</translation>
    </message>
  </context>
  <context>
    <name>ATOMICGUI_AddAtomDlg</name>
    <message>
      <source>CAPTION</source>
      <translation>CAPTION</translation>
    </message>
  </context>
</TS>
