<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>Yacsgui</name>
    <message>
      <source>PREF_TAB_GENERAL</source>
      <translation>PREF_TAB_GENERAL</translation>
    </message>
    <message>
      <source>PREF_GROUP_COMPONENT</source>
      <translation>PREF_GROUP_COMPONENT</translation>
    </message>
    <message>
      <source>PREF_TAB_STATE</source>
      <translation>PREF_TAB_STATE</translation>
    </message>
    <message>
      <source>PREF_GROUP_EDIT</source>
      <translation>PREF_GROUP_EDIT</translation>
    </message>
    <message>
      <source>PREF_GROUP_RUN</source>
      <translation>PREF_GROUP_RUN</translation>
    </message>
    <message>
      <source>PREF_TAB_NODE</source>
      <translation>PREF_TAB_NODE</translation>
    </message>
    <message>
      <source>PREF_GROUP_SCENE</source>
      <translation>PREF_GROUP_SCENE</translation>
    </message>
    <message>
      <source>PREF_GROUP_BLOC</source>
      <translation>PREF_GROUP_BLOC</translation>
    </message>
    <message>
      <source>PREF_GROUP_NODE</source>
      <translation>PREF_GROUP_NODE</translation>
    </message>
    <message>
      <source>PREF_GROUP_HEADER</source>
      <translation>PREF_GROUP_HEADER</translation>
    </message>
    <message>
      <source>PREF_GROUP_CONTROL</source>
      <translation>PREF_GROUP_CONTROL</translation>
    </message>
    <message>
      <source>PREF_GROUP_PORT</source>
      <translation>PREF_GROUP_PORT</translation>
    </message>
    <message>
      <source>PREF_GROUP_DRAG</source>
      <translation>PREF_GROUP_DRAG</translation>
    </message>
    <message>
      <source>PREF_GROUP_GENERAL</source>
      <translation>PREF_GROUP_GENERAL</translation>
    </message>
    <message>
      <source>COMPONENT_INSTANCE_NEW</source>
      <translation>COMPONENT_INSTANCE_NEW</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>ERROR</translation>
    </message>
    <message>
      <source>YACS_PLUGINS</source>
      <translation>YACS_PLUGINS</translation>
    </message>
  </context>
</TS>
