<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>BLSURF_MESH_TYPE</source>
      <translation>メッシュの種類</translation>
    </message>
    <message>
      <source>BLSURF_PHY_MESH</source>
      <translation>物理的なメッシュ</translation>
    </message>
    <message>
      <source>BLSURF_PHY_MESH_TOOLTIP</source>
      <translation>&lt;b&gt;&lt;u&gt;物理的なサイズ モード&lt;/u&gt;&lt;/b&gt;&lt;br&gt;&lt;br&gt;-「グローバル サイズ」: 物理的なサイズはグローバルであり、提供されるグローバルの物理的なサイズ、メッシュ作成を使用します。 &lt;br&gt;-「ローカル サイズ」: 曲線と関連付けられている物理 sizemap 関数を使用してサーフェス サイズはローカルで計算されます。 &lt;br&gt;-"なし": 物理的なサイズは計算されません。</translation>
    </message>
    <message>
      <source>BLSURF_GEOM_MESH</source>
      <translation>幾何学的なメッシュ</translation>
    </message>
    <message>
      <source>BLSURF_GEOM_MESH_TOOLTIP</source>
      <translation>&lt;b&gt;&lt;u&gt;幾何学的サイズ モード&lt;/u&gt;&lt;/b&gt;&lt;br&gt;&lt;br&gt;-「グローバル サイズ」: 幾何学的なサイズはグローバル、メッシュ作成、幾何学的パラメーターで指定された幾何学的な近似を使用する.&lt;br&gt;-「なし」: 幾何学的なサイズは計算されません。</translation>
    </message>
    <message>
      <source>BLSURF_DEFAULT_USER</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>GLOBAL_SIZE</source>
      <translation>グローバル サイズ</translation>
    </message>
    <message>
      <source>LOCAL_SIZE</source>
      <translation>ローカルのサイズ</translation>
    </message>
    <message>
      <source>BLSURF_MAIN_PARAMETERS</source>
      <translation>主なパラメーター</translation>
    </message>
    <message>
      <source>BLSURF_HPHYDEF</source>
      <translation>ユーザーのサイズ</translation>
    </message>
    <message>
      <source>BLSURF_HPHYDEF_TOOLTIP</source>
      <translation>グローバルな定数のサイズを定義します。&lt;br&gt;既定値計算値である &lt;em&gt;diag&lt;/em&gt;/&lt;em&gt;比&lt;/em&gt; &lt;em&gt;の比率&lt;/em&gt; が、環境設定で定義されています。</translation>
    </message>
    <message>
      <source>BLSURF_MINSIZE</source>
      <translation>最小サイズ</translation>
    </message>
    <message>
      <source>BLSURF_MINSIZE_TOOLTIP</source>
      <translation>必要なグローバル セルの最小サイズを定義します。&lt;br&gt;既定値計算値である &lt;em&gt;diag&lt;/em&gt;/1000年。</translation>
    </message>
    <message>
      <source>BLSURF_MAXSIZE</source>
      <translation>最大サイズ</translation>
    </message>
    <message>
      <source>BLSURF_MAXSIZE_TOOLTIP</source>
      <translation>必要なグローバル最大セル サイズを定義します。&lt;br&gt;既定値計算値である &lt;em&gt;diag&lt;/em&gt;/5。</translation>
    </message>
    <message>
      <source>BLSURF_SIZE_REL</source>
      <translation>相対値</translation>
    </message>
    <message>
      <source>BLSURF_SIZE_REL_TOOLTIP</source>
      <translation>&lt;em&gt;Diag&lt;/em&gt; を基準値であります。</translation>
    </message>
    <message>
      <source>BLSURF_GRADATION</source>
      <translation>グラデーション</translation>
    </message>
    <message>
      <source>BLSURF_GRADATION_TOOLTIP</source>
      <translation>最大 2 つの隣接するエッジの長さの比率。</translation>
    </message>
    <message>
      <source>BLSURF_ALLOW_QUADRANGLES</source>
      <translation>四角形を許可します。</translation>
    </message>
    <message>
      <source>BLSURF_GEOMETRICAL_PARAMETERS</source>
      <translation>幾何学的パラメーター</translation>
    </message>
    <message>
      <source>BLSURF_ANGLE_MESH</source>
      <translation>メッシュの角度</translation>
    </message>
    <message>
      <source>BLSURF_ANGLE_MESH_TOOLTIP</source>
      <translation>メッシュの三角形の平面と 3 つの頂点位置の接面の間の角度を制限します。&lt;br&gt;のうち、小さい方はこの角度、近いメッシュは、正確な表面にしの結果、高密度のメッシュです。</translation>
    </message>
    <message>
      <source>BLSURF_CHORDAL_ERROR</source>
      <translation>メッシュの距離</translation>
    </message>
    <message>
      <source>BLSURF_CHORDAL_TOOLTIP</source>
      <translation>三角形とそのサポート CAD 表面間の最大の必要な距離。&lt;br&gt;のうち小さい方のこの距離は、メッシュ、正確な表面 (等方性メッシュでのみ使用可能) に近づきますです。</translation>
    </message>
    <message>
      <source>BLSURF_OTHER_PARAMETERS</source>
      <translation>その他のパラメーター</translation>
    </message>
    <message>
      <source>BLSURF_ANISOTROPIC</source>
      <translation>異方性</translation>
    </message>
    <message>
      <source>BLSURF_ANISOTROPIC_TOOLTIP</source>
      <translation>チェックした場合、このパラメーターには最大異方性比の異方性メッシュ プロセスを支配するメトリックを定義します。&lt;br&gt;既定値 0、メトリック (および生成された要素) が任意に伸ばすことができることを意味します。</translation>
    </message>
    <message>
      <source>BLSURF_REMOVE_TINY_EDGES</source>
      <translation>小さなエッジを削除します。</translation>
    </message>
    <message>
      <source>BLSURF_REMOVE_TINY_EDGES_TOOLTIP</source>
      <translation>チェックした場合、このパラメーターは、エッジが小さなものとして最小の長さを定義します。</translation>
    </message>
    <message>
      <source>BLSURF_REMOVE_SLIVERS</source>
      <translation>悪い要素を削除します。</translation>
    </message>
    <message>
      <source>BLSURF_REMOVE_SLIVERS_TOOLTIP</source>
      <translation>チェックした場合、このパラメーターは「悪い要素」分類をトリガー アスペクト比を定義します。</translation>
    </message>
    <message>
      <source>BLSURF_OPTIMISATION</source>
      <translation>メッシュの最適化</translation>
    </message>
    <message>
      <source>BLSURF_OPTIMISATION_TOOLTIP</source>
      <translation>チェックした場合、MeshGems CADSurf はより良い要素の形を取得するために、メッシュを最適化します。</translation>
    </message>
    <message>
      <source>BLSURF_ELEMENT_ORDER</source>
      <translation>2 次メッシュ</translation>
    </message>
    <message>
      <source>BLSURF_HYPOTHESIS</source>
      <translation>BLSURF 2次元</translation>
    </message>
    <message>
      <source>BLSURF_ADV_ARGS</source>
      <translation>高度な</translation>
    </message>
    <message>
      <source>BLSURF_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>BLSURF_TOPOLOGY</source>
      <translation>トポロジ</translation>
    </message>
    <message>
      <source>BLSURF_TOPOLOGY_CAD</source>
      <translation>CAD</translation>
    </message>
    <message>
      <source>BLSURF_TOPOLOGY_PROCESS</source>
      <translation>前処理</translation>
    </message>
    <message>
      <source>BLSURF_TOPOLOGY_PROCESS2</source>
      <translation>前処理 + +</translation>
    </message>
    <message>
      <source>BLSURF_TOPOLOGY_PRECAD</source>
      <translation>PreCAD</translation>
    </message>
    <message>
      <source>BLSURF_VERBOSITY</source>
      <translation>詳細レベル</translation>
    </message>
    <message>
      <source>OBLIGATORY_VALUE</source>
      <translation>(固定値)</translation>
    </message>
    <message>
      <source>OPTION_TYPE_COLUMN</source>
      <translation>タイプ</translation>
    </message>
    <message>
      <source>OPTION_NAME_COLUMN</source>
      <translation>オプション</translation>
    </message>
    <message>
      <source>OPTION_VALUE_COLUMN</source>
      <translation>値</translation>
    </message>
    <message>
      <source>OPTION_MENU_BLSURF</source>
      <translation>BLSURF</translation>
    </message>
    <message>
      <source>OPTION_MENU_PRECAD</source>
      <translation>PreCAD</translation>
    </message>
    <message>
      <source>BLSURF_ADD_OPTION</source>
      <translation>オプションを追加します。</translation>
    </message>
    <message>
      <source>BLSURF_REMOVE_OPTION</source>
      <translation>Clear オプション</translation>
    </message>
    <message>
      <source>BLSURF_GMF_FILE</source>
      <translation>組み換えをエクスポートします。</translation>
    </message>
    <message>
      <source>BLSURF_GMF_MODE</source>
      <translation>バイナリ</translation>
    </message>
    <message>
      <source>BLSURF_GMF_FILE_DIALOG</source>
      <translation>組み換えファイルを選択します.</translation>
    </message>
    <message>
      <source>BLSURF_GMF_FILE_FORMAT</source>
      <translation>組み換えファイル (*.mesh *.meshb)</translation>
    </message>
    <message>
      <source>BLSURF_PRECAD_GROUP</source>
      <translation>PreCAD オプション</translation>
    </message>
    <message>
      <source>BLSURF_PRECAD_MERGE_EDGES</source>
      <translation>エッジをマージします。</translation>
    </message>
    <message>
      <source>BLSURF_PRECAD_PROCESS_3D_TOPOLOGY</source>
      <translation>プロセス 3 D トポロジ</translation>
    </message>
    <message>
      <source>BLSURF_PRECAD_DISCARD_INPUT</source>
      <translation>入力トポロジを破棄します。</translation>
    </message>
    <message>
      <source>SMP_ENTRY_COLUMN</source>
      <translation>エントリ</translation>
    </message>
    <message>
      <source>SMP_NAME_COLUMN</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>SMP_SIZEMAP_COLUMN</source>
      <translation>ローカルのサイズ</translation>
    </message>
    <message>
      <source>BLSURF_SM_SURFACE</source>
      <translation>顔 (またはグループ)</translation>
    </message>
    <message>
      <source>BLSURF_SM_EDGE</source>
      <translation>エッジ (またはグループ)</translation>
    </message>
    <message>
      <source>BLSURF_SM_POINT</source>
      <translation>ポイント (またはグループ)</translation>
    </message>
    <message>
      <source>BLSURF_SM_ATTRACTOR</source>
      <translation>アトラクターを追加します。</translation>
    </message>
    <message>
      <source>BLSURF_SM_STD_TAB</source>
      <translation>簡易マップ</translation>
    </message>
    <message>
      <source>BLSURF_SM_ATT_TAB</source>
      <translation>高度な</translation>
    </message>
    <message>
      <source>BLSURF_SM_PARAMS</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>BLSURF_ATTRACTOR</source>
      <translation>アトラクター</translation>
    </message>
    <message>
      <source>BLSURF_CONST_SIZE</source>
      <translation>定数のサイズ] 図形の近く</translation>
    </message>
    <message>
      <source>BLSURF_ATT_DIST</source>
      <translation>ディストリクトに影響を与える</translation>
    </message>
    <message>
      <source>BLSURF_ATT_RADIUS</source>
      <translation>一定以上</translation>
    </message>
    <message>
      <source>BLSURF_SM_SIZE</source>
      <translation>ローカルのサイズ</translation>
    </message>
    <message>
      <source>BLSURF_SM_DIST</source>
      <translation>距離</translation>
    </message>
    <message>
      <source>BLS_SEL_SHAPE</source>
      <translation>図形を選択します。</translation>
    </message>
    <message>
      <source>BLS_SEL_VERTICES</source>
      <translation>頂点を選択します</translation>
    </message>
    <message>
      <source>BLS_SEL_FACE</source>
      <translation>面を選択します。</translation>
    </message>
    <message>
      <source>BLS_SEL_FACES</source>
      <translation>面を選択します</translation>
    </message>
    <message>
      <source>BLS_SEL_ATTRACTOR</source>
      <translation>アトラクターを選択します。</translation>
    </message>
    <message>
      <source>BLSURF_SM_ADD</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>BLSURF_SM_MODIFY</source>
      <translation>変更します。</translation>
    </message>
    <message>
      <source>BLSURF_SM_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>BLSURF_SM_SURF_VALUE</source>
      <translation>面サイズ</translation>
    </message>
    <message>
      <source>BLSURF_SM_EDGE_VALUE</source>
      <translation>サイズに保ちます</translation>
    </message>
    <message>
      <source>BLSURF_SM_POINT_VALUE</source>
      <translation>ポイント サイズ</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER</source>
      <translation>適用された頂点</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_FACE_ENTRY_COLUMN</source>
      <translation>顔のエントリ</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_NAME_COLUMN</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_X_COLUMN</source>
      <translation>X</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_Y_COLUMN</source>
      <translation>Y</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_Z_COLUMN</source>
      <translation>Z</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_ENTRY_COLUMN</source>
      <translation>頂点のエントリ</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_GROUP_COLUMN</source>
      <translation>グループ</translation>
    </message>
    <message>
      <source>BLSURF_ENF_SELECT_FACE</source>
      <translation>面を選択します。</translation>
    </message>
    <message>
      <source>BLSURF_ENF_SELECT_VERTEX</source>
      <translation>頂点を選択します</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_X_LABEL</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_Y_LABEL</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_Z_LABEL</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_GROUP_LABEL</source>
      <translation>グループ:</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_VERTEX</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>BLSURF_ENF_VER_INTERNAL_VERTICES</source>
      <translation>すべての面の内部頂点を使用します。</translation>
    </message>
  </context>
</TS>
