<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>SMESH_ARITHMETIC_1D_HYPOTHESIS</source>
      <translation>SMESH_ARITHMETIC_1D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_ARITHMETIC_1D_PARAM</source>
      <translation>SMESH_ARITHMETIC_1D_PARAM</translation>
    </message>
    <message>
      <source>SMESH_ARITHMETIC_1D_TITLE</source>
      <translation>SMESH_ARITHMETIC_1D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_AUTOMATIC_LENGTH_HYPOTHESIS</source>
      <translation>SMESH_AUTOMATIC_LENGTH_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_AUTOMATIC_LENGTH_TITLE</source>
      <translation>SMESH_AUTOMATIC_LENGTH_TITLE</translation>
    </message>
    <message>
      <source>SMESH_CONV_MODE</source>
      <translation>SMESH_CONV_MODE</translation>
    </message>
    <message>
      <source>SMESH_CUT_NEG_MODE</source>
      <translation>SMESH_CUT_NEG_MODE</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_HYPOTHESIS</source>
      <translation>SMESH_DEFLECTION1D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_PARAM</source>
      <translation>SMESH_DEFLECTION1D_PARAM</translation>
    </message>
    <message>
      <source>SMESH_DEFLECTION1D_TITLE</source>
      <translation>SMESH_DEFLECTION1D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_DENSITY_FUNC</source>
      <translation>SMESH_DENSITY_FUNC</translation>
    </message>
    <message>
      <source>SMESH_DISTR</source>
      <translation>SMESH_DISTR</translation>
    </message>
    <message>
      <source>SMESH_DISTR_EXPR</source>
      <translation>SMESH_DISTR_EXPR</translation>
    </message>
    <message>
      <source>SMESH_DISTR_REGULAR</source>
      <translation>SMESH_DISTR_REGULAR</translation>
    </message>
    <message>
      <source>SMESH_DISTR_SCALE</source>
      <translation>SMESH_DISTR_SCALE</translation>
    </message>
    <message>
      <source>SMESH_DISTR_TAB</source>
      <translation>SMESH_DISTR_TAB</translation>
    </message>
    <message>
      <source>SMESH_DISTR_TYPE</source>
      <translation>SMESH_DISTR_TYPE</translation>
    </message>
    <message>
      <source>SMESH_END_LENGTH_PARAM</source>
      <translation>SMESH_END_LENGTH_PARAM</translation>
    </message>
    <message>
      <source>SMESH_EXPR_FUNC</source>
      <translation>SMESH_EXPR_FUNC</translation>
    </message>
    <message>
      <source>SMESH_EXP_MODE</source>
      <translation>SMESH_EXP_MODE</translation>
    </message>
    <message>
      <source>SMESH_FINENESS_PARAM</source>
      <translation>SMESH_FINENESS_PARAM</translation>
    </message>
    <message>
      <source>SMESH_FUNC_DOMAIN</source>
      <translation>SMESH_FUNC_DOMAIN</translation>
    </message>
    <message>
      <source>SMESH_INSERT_ROW</source>
      <translation>SMESH_INSERT_ROW</translation>
    </message>
    <message>
      <source>SMESH_INVALID_FUNCTION</source>
      <translation>SMESH_INVALID_FUNCTION</translation>
    </message>
    <message>
      <source>SMESH_LAYERS_DISTRIBUTION</source>
      <translation>SMESH_LAYERS_DISTRIBUTION</translation>
    </message>
    <message>
      <source>SMESH_LAYER_DISTRIBUTION_HYPOTHESIS</source>
      <translation>SMESH_LAYER_DISTRIBUTION_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_LAYER_DISTRIBUTION_TITLE</source>
      <translation>SMESH_LAYER_DISTRIBUTION_TITLE</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_HYPOTHESIS</source>
      <translation>SMESH_LOCAL_LENGTH_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_PARAM</source>
      <translation>SMESH_LOCAL_LENGTH_PARAM</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_PRECISION</source>
      <translation>SMESH_LOCAL_LENGTH_PRECISION</translation>
    </message>
    <message>
      <source>SMESH_LOCAL_LENGTH_TITLE</source>
      <translation>SMESH_LOCAL_LENGTH_TITLE</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS_1D_HYPOTHESIS</source>
      <translation>SMESH_FIXED_POINTS_1D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS_1D_TITLE</source>
      <translation>SMESH_FIXED_POINTS_1D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_MAX_LENGTH_HYPOTHESIS</source>
      <translation>SMESH_MAX_LENGTH_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_CARTESIAN_PARAMS_HYPOTHESIS</source>
      <translation>SMESH_CARTESIAN_PARAMS_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_USE_PREESTIMATED_LENGTH</source>
      <translation>SMESH_USE_PREESTIMATED_LENGTH</translation>
    </message>
    <message>
      <source>SMESH_VISCOUS_LAYERS_HYPOTHESIS</source>
      <translation>SMESH_VISCOUS_LAYERS_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_VISCOUS_LAYERS_TITLE</source>
      <translation>SMESH_VISCOUS_LAYERS_TITLE</translation>
    </message>
    <message>
      <source>SMESH_TOTAL_THICKNESS</source>
      <translation>SMESH_TOTAL_THICKNESS</translation>
    </message>
    <message>
      <source>SMESH_STRETCH_FACTOR</source>
      <translation>SMESH_STRETCH_FACTOR</translation>
    </message>
    <message>
      <source>SMESH_FACES_WO_LAYERS</source>
      <translation>SMESH_FACES_WO_LAYERS</translation>
    </message>
    <message>
      <source>SMESH_EDGES_WO_LAYERS</source>
      <translation>SMESH_EDGES_WO_LAYERS</translation>
    </message>
    <message>
      <source>SMESH_MAX_LENGTH_TITLE</source>
      <translation>SMESH_MAX_LENGTH_TITLE</translation>
    </message>
    <message>
      <source>SMESH_CARTESIAN_PARAMS_TITLE</source>
      <translation>SMESH_CARTESIAN_PARAMS_TITLE</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_HYPOTHESIS</source>
      <translation>SMESH_MAX_ELEMENT_AREA_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_PARAM</source>
      <translation>SMESH_MAX_ELEMENT_AREA_PARAM</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_AREA_TITLE</source>
      <translation>SMESH_MAX_ELEMENT_AREA_TITLE</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_HYPOTHESIS</source>
      <translation>SMESH_MAX_ELEMENT_VOLUME_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_PARAM</source>
      <translation>SMESH_MAX_ELEMENT_VOLUME_PARAM</translation>
    </message>
    <message>
      <source>SMESH_MAX_ELEMENT_VOLUME_TITLE</source>
      <translation>SMESH_MAX_ELEMENT_VOLUME_TITLE</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_HYPOTHESIS</source>
      <translation>SMESH_NB_SEGMENTS_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_PARAM</source>
      <translation>SMESH_NB_SEGMENTS_PARAM</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_SCALE_PARAM</source>
      <translation>SMESH_NB_SEGMENTS_SCALE_PARAM</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS_TITLE</source>
      <translation>SMESH_NB_SEGMENTS_TITLE</translation>
    </message>
    <message>
      <source>SMESH_NO_CONV</source>
      <translation>SMESH_NO_CONV</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS</source>
      <translation>SMESH_NUMBER_OF_LAYERS</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_HYPOTHESIS</source>
      <translation>SMESH_NUMBER_OF_LAYERS_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_2D_HYPOTHESIS</source>
      <translation>SMESH_NUMBER_OF_LAYERS_2D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_TITLE</source>
      <translation>SMESH_NUMBER_OF_LAYERS_TITLE</translation>
    </message>
    <message>
      <source>SMESH_NUMBER_OF_LAYERS_2D_TITLE</source>
      <translation>SMESH_NUMBER_OF_LAYERS_2D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_1D_HYPOTHESIS</source>
      <translation>SMESH_PROJECTION_SOURCE_1D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_1D_TITLE</source>
      <translation>SMESH_PROJECTION_SOURCE_1D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_2D_HYPOTHESIS</source>
      <translation>SMESH_PROJECTION_SOURCE_2D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_2D_TITLE</source>
      <translation>SMESH_PROJECTION_SOURCE_2D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_3D_HYPOTHESIS</source>
      <translation>SMESH_PROJECTION_SOURCE_3D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_PROJECTION_SOURCE_3D_TITLE</source>
      <translation>SMESH_PROJECTION_SOURCE_3D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_1D_HYPOTHESIS</source>
      <translation>SMESH_IMPORT_SOURCE_1D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_1D_TITLE</source>
      <translation>SMESH_IMPORT_SOURCE_1D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_2D_HYPOTHESIS</source>
      <translation>SMESH_IMPORT_SOURCE_2D_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_IMPORT_SOURCE_2D_TITLE</source>
      <translation>SMESH_IMPORT_SOURCE_2D_TITLE</translation>
    </message>
    <message>
      <source>SMESH_REMOVE_ROW</source>
      <translation>SMESH_REMOVE_ROW</translation>
    </message>
    <message>
      <source>SMESH_REVERSED_EDGES</source>
      <translation>SMESH_REVERSED_EDGES</translation>
    </message>
    <message>
      <source>SMESH_FIXED_POINTS</source>
      <translation>SMESH_FIXED_POINTS</translation>
    </message>
    <message>
      <source>SMESH_RANGE</source>
      <translation>SMESH_RANGE</translation>
    </message>
    <message>
      <source>SMESH_NB_SEGMENTS</source>
      <translation>SMESH_NB_SEGMENTS</translation>
    </message>
    <message>
      <source>SMESH_SAME_NB_SEGMENTS</source>
      <translation>SMESH_SAME_NB_SEGMENTS</translation>
    </message>
    <message>
      <source>SMESH_BASE_VERTEX</source>
      <translation>SMESH_BASE_VERTEX</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_HYPOTHESIS</source>
      <translation>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_PARAM</source>
      <translation>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_PARAM</translation>
    </message>
    <message>
      <source>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_TITLE</source>
      <translation>SMESH_SEGMENT_LENGTH_AROUND_VERTEX_TITLE</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_3DSHAPE</source>
      <translation>SMESH_SOURCE_3DSHAPE</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_EDGE</source>
      <translation>SMESH_SOURCE_EDGE</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_EDGES</source>
      <translation>SMESH_SOURCE_EDGES</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_FACE</source>
      <translation>SMESH_SOURCE_FACE</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_FACES</source>
      <translation>SMESH_SOURCE_FACES</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_MESH</source>
      <translation>SMESH_SOURCE_MESH</translation>
    </message>
    <message>
      <source>SMESH_COPY_MESH</source>
      <translation>SMESH_COPY_MESH</translation>
    </message>
    <message>
      <source>SMESH_TO_COPY_GROUPS</source>
      <translation>SMESH_TO_COPY_GROUPS</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX</source>
      <translation>SMESH_SOURCE_VERTEX</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX1</source>
      <translation>SMESH_SOURCE_VERTEX1</translation>
    </message>
    <message>
      <source>SMESH_SOURCE_VERTEX2</source>
      <translation>SMESH_SOURCE_VERTEX2</translation>
    </message>
    <message>
      <source>SMESH_START_END_LENGTH_HYPOTHESIS</source>
      <translation>SMESH_START_END_LENGTH_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_START_END_LENGTH_TITLE</source>
      <translation>SMESH_START_END_LENGTH_TITLE</translation>
    </message>
    <message>
      <source>SMESH_START_LENGTH_PARAM</source>
      <translation>SMESH_START_LENGTH_PARAM</translation>
    </message>
    <message>
      <source>SMESH_TAB_FUNC</source>
      <translation>SMESH_TAB_FUNC</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX</source>
      <translation>SMESH_TARGET_VERTEX</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX1</source>
      <translation>SMESH_TARGET_VERTEX1</translation>
    </message>
    <message>
      <source>SMESH_TARGET_VERTEX2</source>
      <translation>SMESH_TARGET_VERTEX2</translation>
    </message>
    <message>
      <source>SMESH_QUADRANGLE_PARAMS_HYPOTHESIS</source>
      <translation>SMESH_QUADRANGLE_PARAMS_HYPOTHESIS</translation>
    </message>
    <message>
      <source>SMESH_QUADRANGLE_PARAMS_TITLE</source>
      <translation>SMESH_QUADRANGLE_PARAMS_TITLE</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE</source>
      <translation>SMESH_QUAD_TYPE</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_QuadrangleParamWdg</name>
    <message>
      <source>SMESH_QUAD_TYPE_0</source>
      <translation>SMESH_QUAD_TYPE_0</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_1</source>
      <translation>SMESH_QUAD_TYPE_1</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_2</source>
      <translation>SMESH_QUAD_TYPE_2</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_3</source>
      <translation>SMESH_QUAD_TYPE_3</translation>
    </message>
    <message>
      <source>SMESH_QUAD_TYPE_4</source>
      <translation>SMESH_QUAD_TYPE_4</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_LayerDistributionParamWdg</name>
    <message>
      <source>CHANGE_TYPE</source>
      <translation>CHANGE_TYPE</translation>
    </message>
    <message>
      <source>CREATE</source>
      <translation>CREATE</translation>
    </message>
    <message>
      <source>EDIT</source>
      <translation>EDIT</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI_CartesianParamCreator</name>
    <message>
      <source>THRESHOLD</source>
      <translation>THRESHOLD</translation>
    </message>
    <message>
      <source>AXIS_X</source>
      <translation>AXIS_X</translation>
    </message>
    <message>
      <source>AXIS_Y</source>
      <translation>AXIS_Y</translation>
    </message>
    <message>
      <source>AXIS_Z</source>
      <translation>AXIS_Z</translation>
    </message>
  </context>
  <context>
    <name>StdMeshersGUI::GridAxisTab</name>
    <message>
      <source>GRID_DEF_MODE</source>
      <translation>GRID_DEF_MODE</translation>
    </message>
    <message>
      <source>SPACING</source>
      <translation>SPACING</translation>
    </message>
    <message>
      <source>INSERT</source>
      <translation>INSERT</translation>
    </message>
    <message>
      <source>COORD_STEP</source>
      <translation>COORD_STEP</translation>
    </message>
  </context>
</TS>
