<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>Yacsgui</name>
    <message>
      <source>PREF_TAB_GENERAL</source>
      <translation>一般的な</translation>
    </message>
    <message>
      <source>PREF_GROUP_COMPONENT</source>
      <translation>コンポーネント</translation>
    </message>
    <message>
      <source>PREF_TAB_STATE</source>
      <translation>ノードの状態</translation>
    </message>
    <message>
      <source>PREF_GROUP_EDIT</source>
      <translation>状態を編集します。</translation>
    </message>
    <message>
      <source>PREF_GROUP_RUN</source>
      <translation>実行状態</translation>
    </message>
    <message>
      <source>PREF_TAB_NODE</source>
      <translation>ノード</translation>
    </message>
    <message>
      <source>PREF_GROUP_SCENE</source>
      <translation>シーン</translation>
    </message>
    <message>
      <source>PREF_GROUP_BLOC</source>
      <translation>ブロック</translation>
    </message>
    <message>
      <source>PREF_GROUP_NODE</source>
      <translation>ノード</translation>
    </message>
    <message>
      <source>PREF_GROUP_HEADER</source>
      <translation>ヘッダー</translation>
    </message>
    <message>
      <source>PREF_GROUP_CONTROL</source>
      <translation>制御ポート</translation>
    </message>
    <message>
      <source>PREF_GROUP_PORT</source>
      <translation>データフロー ポート</translation>
    </message>
    <message>
      <source>PREF_GROUP_DRAG</source>
      <translation>ドラッグ</translation>
    </message>
    <message>
      <source>PREF_GROUP_GENERAL</source>
      <translation>一般的な</translation>
    </message>
    <message>
      <source>COMPONENT_INSTANCE_NEW</source>
      <translation>各新しいサービス ノードのコンポーネント インスタンスを作成します。</translation>
    </message>
    <message>
      <source>ERROR</source>
      <translation>エラー</translation>
    </message>
    <message>
      <source>YACS_PLUGINS</source>
      <translation>プラグイン</translation>
    </message>
  </context>
</TS>
